[variables]
APP_ENV = "production"

[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build && rm -rf node_modules && mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache && chmod -R a+rw storage bootstrap/cache && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan event:cache"

[build.env]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
