[variables]
APP_ENV = "production"

[build]
builder = "NIXPACKS"
buildCommand = "set -ex; composer install --no-dev --optimize-autoloader; npm ci; npm run build; rm -rf node_modules; test ! -d node_modules; mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache; chmod -R a+rw storage bootstrap/cache; php artisan config:cache; php artisan route:cache; php artisan view:cache; php artisan event:cache; ls -a"

[build.env]
NIXPACKS_NODE_VERSION = "22.12.0"
NODE_VERSION = "22.12.0"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
